version: 2

project_name: taskboard-mcp

before:
  hooks:
    - go mod tidy

builds:
  - id: taskboard-mcp
    main: .
    binary: taskboard-mcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  github:
    owner: MnemoShare
    name: projectboard-mcp
  draft: false
  prerelease: auto

brews:
  - name: taskboard-mcp
    repository:
      owner: MnemoShare
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    folder: Formula
    homepage: "https://github.com/MnemoShare/projectboard-mcp"
    description: "MCP server for TaskBoard - enables AI assistants to manage tasks"
    license: "MIT"
    skip_upload: auto
